# -*- coding: utf-8 -*-
"""Codemon.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PGr-6ZmEYNmOV_sUz4-1mucd3TFQ2hw8
"""

pip install requests

import requests

#Questions
Logic_questions = ""

#MonsterSheet
class Monster:
  name = ""
  HP = 1
  LVL = 1