# -*- coding: utf-8 -*-
"""Codemon.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PGr-6ZmEYNmOV_sUz4-1mucd3TFQ2hw8
"""

import os
import random
import requests
import time
import sys

# Configuració inicial
respuesta = requests.get("https://fun.codelearn.cat/hackathon/game/new")
print(respuesta.status_code)
dades = respuesta.json()

def clear_screen():
    os.system('cls' if os.name == 'nt' else 'clear')

player_art = r"""
   \O/
    |
   / \
 Tu (Heroi)
"""

# Monstres amb art ASCII millorat
monster_ascii = {
    "Marrameu": r"""
    |\___/|
   (= o_o =)
   (")___(")
 Marrameu
""",
    "Pyrosaur": r"""
    /^ ^\
   / 0 0 \
   V\ Y /V
    / - \
   |    |
   || (__)
 Pyrosaur
""",
    "Bugzilla": r"""
    .-'      '-.
   /            \
  |    O   O    |
   \.--. .--./
   (    Y    )
    \__^__/
  Bugzilla
""",
    "Stacktoise": r"""
   _____     ____
  /     \~~~/    \\
 (  o  o ) ( o o  )
  \__^__/   \_^__/
  /     \___/     \\
 |               |
 |__|_|_|___|_|__|
Stacktoise
""",
    "Nullphant": r"""
     _.-- ,.--.
   .'   .'     /
   | @       |'..--------._
  /      \._/              '.
 /  .-.-                     \
(  /    \                     \\
 \\      '.                  | #
  \\       \   -.           /
   :\       |    )._____.'   \
    "       |   /  \  |  \    )
            |   |./'  :__ \.-'
            '--'
Nullphant
""",
    "Indentarion": r"""
     ,     ,
    (\____/)
     (_oo_)
     (O  O)
    /   \/\
   (__/\__)
   | |  | |
  /_/|__|_\
 Indentarion
""",
    "Dracorix": r"""
      /^\/^\
    _|__|  O|
\/     /~  \
 \____|__________/  \
        \_______      \
                `\     \                 \
                  |     |                  \
                 /      /                    \
                /     /                       \
              /      /                         \ \
             /     /                            \  \
           /     /             _----_            \   \
          /     /           _-~      ~-_         |   |
         (      (        _-~    _--_    ~-_     _/   |
          \      ~-____-~    _-~    ~-_    ~-_-~    /
            ~-_           _-~          ~-_       _-~
               ~--______-~                ~-___-~
Dracorix
""",
    "Toxicorn": r"""
      .     .
       \___/
      (o o)
      / V \
     /(   )\
     ^^   ^^
  Toxicorn
""",
    "Cryptodon": r"""
     .-=-.
    /  !  \
   |      |
   |  .-. |
   |  | | |
   |  '-' |
    \     /
     `---`
 Cryptodon
""",
    "Voltigon": r"""
     \     /
      \   /
       \_/
       |=|
      __|__
     /     \
    |  ⚡  |
     \___/
 Voltigon
""",
    "Octopulse": r"""
   _____
  /     \
 | () () |
  \  ^  /
   |||||
   |||||
 Octopulse
""",
    "JavaDog": r"""
    |\_/|
  | @ @   Buf!
  |   <>
  |  _/\
  | |  |
 JavaDog
""",
    "CookieHamster": r"""
      (\_/)
    ( •_•)
   / >🍪
 CookieHamster
""",
    "HDCat": r"""
        ,_     _
    |\\_,-~/
    / _  _ |    ,--.
   (  @  @ )   / ,-'
    \  _T_/-._( (
    /         `. \
   |         _  \ |
    \ \ ,  /      |
     || |-_\__   /
    ((_/`(____,-'
 HDCat
""",
    "CCSD": r"""
       .-----.
  / .===. \
  \/ 6 6 \/
  ( \_=_/ )
   ^^---^^
 CCSD
"""
}

# Jefes especials
bosses = {
    "Megadrac": {
        "HP": 500,
        "LVL": 10,
        "ATTACK": 35,
        "art": r"""
        / \    / \
       /   \  /   \
      /     \/     \
     /             \
    /      /\      \
   /      /  \      \
  /      /    \      \
 /      /      \      \
/______/        \______\
|                     |
|                     |
|        MEGADRAC     |
|_____________________|
"""
    },
    "Cibertroll": {
        "HP": 450,
        "LVL": 15,
        "ATTACK": 40,
        "art": r"""
      .-""-.
     / .--. \
    / /    \ \
   | |      | |
   | |.----.| |
    \  o   o  /
     '------'
    / _-""-._ \
   /  / __ \  \
  |   |'  '|   |
  |   | || |   |
  |   | || |   |
  '---' '' '---'
  CIBERTROLL
"""
    }
}

# Preguntes per categoria (30 per categoria)
categorias_preguntas = {
    "1": {
        "nom": "Programació",
        "preguntes": [
            {"pregunta": "Quin llenguatge de programació és conegut per la seva sintaxi clara i s'usa molt en IA?",
             "opcions": ["Python", "Java", "C++"], "resposta": "Python"},
            {"pregunta": "Què significa 'HTML'?",
             "opcions": ["HyperText Markup Language", "HighText Machine Language", "Hyperlink and Text Markup Language"], "resposta": "HyperText Markup Language"},
            {"pregunta": "Per a què s'utilitza principalment SQL?",
             "opcions": ["Gestió de bases de dades", "Disseny web", "Aplicacions mòbils"], "resposta": "Gestió de bases de dades"},
            {"pregunta": "Quina estructura de dades funciona amb el principi FIFO?",
             "opcions": ["Pila (Stack)", "Cua (Queue)", "Arbre (Tree)"], "resposta": "Cua (Queue)"},
            {"pregunta": "Quina és la funció principal d'un compilador?",
             "opcions": ["Executar codi directament", "Convertir codi font a codi màquina", "Depurar errors"], "resposta": "Convertir codi font a codi màquina"},
            {"pregunta": "Què és un bucle 'for'?",
             "opcions": ["Una estructura condicional", "Una estructura repetitiva", "Una funció"], "resposta": "Una estructura repetitiva"},
            {"pregunta": "Quin llenguatge s'utilitza sovint per programar aplicacions web del costat del client?",
             "opcions": ["JavaScript", "Python", "C#"], "resposta": "JavaScript"},
            {"pregunta": "Quin és el resultat de 'print(2 ** 3)' en Python?",
             "opcions": ["6", "8", "9"], "resposta": "8"},
            {"pregunta": "Quin concepte de programació permet executar diferents blocs de codi depenent d'una condició?",
             "opcions": ["Bucle", "Condicional", "Funció"], "resposta": "Condicional"},
            {"pregunta": "Què és un 'array' en programació?",
             "opcions": ["Una funció", "Una col·lecció ordenada d'elements", "Un tipus de variable"], "resposta": "Una col·lecció ordenada d'elements"},
            {"pregunta": "Què és la recursió en programació?",
             "opcions": ["Una funció que es crida a si mateixa", "Un error de codi", "Un tipus de variable"], "resposta": "Una funció que es crida a si mateixa"},
            {"pregunta": "Què és un 'bug' en programació?",
             "opcions": ["Un error en el codi", "Una funció especial", "Una llibreria externa"], "resposta": "Un error en el codi"},
            {"pregunta": "Què significa API?",
             "opcions": ["Application Programming Interface", "Applied Program Integration", "Advanced Programming Interaction"], "resposta": "Application Programming Interface"},
            {"pregunta": "Què és un IDE?",
             "opcions": ["Integrated Development Environment", "Internal Data Engine", "Interactive Design Editor"], "resposta": "Integrated Development Environment"},
            {"pregunta": "Quin llenguatge de programació és famós pel seu ús en desenvolupament d'apps iOS?",
             "opcions": ["Swift", "Kotlin", "Ruby"], "resposta": "Swift"},
            {"pregunta": "Què significa CSS?",
             "opcions": ["Cascading Style Sheets", "Computer Style System", "Creative Style Syntax"], "resposta": "Cascading Style Sheets"},
            {"pregunta": "Què és una variable?",
             "opcions": ["Un contenidor per emmagatzemar dades", "Un tipus de dada específic", "Una funció especial"], "resposta": "Un contenidor per emmagatzemar dades"},
            {"pregunta": "Què és Git?",
             "opcions": ["Un sistema de control de versions", "Un llenguatge de programació", "Un editor de codi"], "resposta": "Un sistema de control de versions"},
            {"pregunta": "Què és la programació orientada a objectes?",
             "opcions": ["Un paradigma basat en objectes i classes", "Una tècnica de depuració", "Una llibreria estàndard"], "resposta": "Un paradigma basat en objectes i classes"},
            {"pregunta": "Què és una funció en programació?",
             "opcions": ["Un bloc de codi que realitza una tasca", "Una variable especial", "Un error comú"], "resposta": "Un bloc de codi que realitza una tasca"},
            {"pregunta": "Què és un loop infinit?",
             "opcions": ["Un bucle que mai acaba", "Un bucle que s'executa una vegada", "Un error de sintaxi"], "resposta": "Un bucle que mai acaba"},
            {"pregunta": "Quin d'aquests és un llenguatge de tipat estàtic?",
             "opcions": ["Python", "JavaScript", "Java"], "resposta": "Java"},
            {"pregunta": "Què fa l'operador '%' en la majoria de llenguatges de programació?",
             "opcions": ["Divisió", "Mòdul (residu)", "Multiplicació"], "resposta": "Mòdul (residu)"},
            {"pregunta": "Què és un framework en programació?",
             "opcions": ["Un entorn de treball predefinit", "Un tipus de biblioteca", "Un llenguatge de programació"], "resposta": "Un entorn de treball predefinit"},
            {"pregunta": "Quin d'aquests serveix per gestionar dependències en Python?",
             "opcions": ["npm", "pip", "gradle"], "resposta": "pip"},
            {"pregunta": "Què és Docker?",
             "opcions": ["Un sistema de contenidors", "Un llenguatge de programació", "Un sistema operatiu"], "resposta": "Un sistema de contenidors"},
            {"pregunta": "Quina empresa va desenvolupar el llenguatge Go?",
             "opcions": ["Google", "Microsoft", "Facebook"], "resposta": "Google"},
            {"pregunta": "Què és la programació funcional?",
             "opcions": ["Un paradigma basat en funcions matemàtiques", "Programació amb funcions", "Programació orientada a objectes"], "resposta": "Un paradigma basat en funcions matemàtiques"},
            {"pregunta": "Què és un punt d'interrupció (breakpoint)?",
             "opcions": ["Un error en el codi", "Un lloc on s'atura l'execució per depurar", "Un tipus de variable"], "resposta": "Un lloc on s'atura l'execució per depurar"}
        ]
    },
    "2": {
        "nom": "Matemàtiques",
        "preguntes": [
            {"pregunta": "Quin és el resultat de 7 x 8?", "opcions": ["54", "56", "64"], "resposta": "56"},
            {"pregunta": "Quina fórmula s'utilitza per calcular l'àrea d'un cercle?",
             "opcions": ["πr²", "2πr", "πd"], "resposta": "πr²"},
            {"pregunta": "Quin és un nombre primer?", "opcions": ["15", "17", "21"], "resposta": "17"},
            {"pregunta": "Quina és la derivada de f(x) = x²?",
             "opcions": ["2x", "x", "x³"], "resposta": "2x"},
            {"pregunta": "Quin és el valor aproximat de π a dos decimals?",
             "opcions": ["3.14", "3.41", "3.04"], "resposta": "3.14"},
            {"pregunta": "Quant sumen els angles interiors d'un triangle?",
             "opcions": ["180 graus", "360 graus", "90 graus"], "resposta": "180 graus"},
            {"pregunta": "Quina és la fórmula per calcular la mitjana aritmètica?",
             "opcions": ["Suma de valors / nombre de valors", "Producte de valors / nombre de valors", "Valor màxim - valor mínim"], "resposta": "Suma de valors / nombre de valors"},
            {"pregunta": "Quin és el nombre e?",
             "opcions": ["2.71", "3.14", "1.62"], "resposta": "2.71"},
            {"pregunta": "Com es diu una línia que toca un cercle en un sol punt?",
             "opcions": ["Secant", "Tangent", "Diàmetre"], "resposta": "Tangent"},
            {"pregunta": "Quin és el resultat de 123 + 456?", "opcions": ["579", "569", "589"], "resposta": "579"},
            {"pregunta": "Què és un nombre racional?",
             "opcions": ["Un nombre que pot expressar-se com a fracció", "Un nombre amb infinits decimals no periòdics", "Un nombre irracional"], "resposta": "Un nombre que pot expressar-se com a fracció"},
            {"pregunta": "Quina és l'arrel quadrada de 64?",
             "opcions": ["6", "8", "16"], "resposta": "8"},
            {"pregunta": "Què és un polígon regular?",
             "opcions": ["Un polígon amb tots els seus costats i angles iguals", "Un polígon amb costats diferents", "Un polígon amb 4 costats"], "resposta": "Un polígon amb tots els seus costats i angles iguals"},
            {"pregunta": "Què és un angle obtús?",
             "opcions": ["Un angle major de 90 graus", "Un angle menor de 90 graus", "Un angle de 90 graus"], "resposta": "Un angle major de 90 graus"},
            {"pregunta": "Què és una funció lineal?",
             "opcions": ["Una funció de la forma f(x) = mx + b", "Una funció amb paràbola", "Una funció constant"], "resposta": "Una funció de la forma f(x) = mx + b"},
            {"pregunta": "Què és el teorema de Pitàgores?",
             "opcions": ["a² + b² = c²", "a + b = c", "a x b = c"], "resposta": "a² + b² = c²"},
            {"pregunta": "Quin és el màxim comú divisor (MCD)?",
             "opcions": ["El nombre més gran que divideix a dos nombres", "El nombre més petit que divideix a dos nombres", "El producte de dos nombres"], "resposta": "El nombre més gran que divideix a dos nombres"},
            {"pregunta": "Què és un nombre irracional?",
             "opcions": ["Un nombre que no pot expressar-se com a fracció", "Un nombre que pot expressar-se com a fracció", "Un nombre enter"], "resposta": "Un nombre que no pot expressar-se com a fracció"},
            {"pregunta": "Què representa el pendent en una gràfica lineal?",
             "opcions": ["La taxa de canvi", "La intersecció", "El domini"], "resposta": "La taxa de canvi"},
            {"pregunta": "Què és un angle recte?",
             "opcions": ["Un angle de 90 graus", "Un angle menor de 90 graus", "Un angle major de 90 graus"], "resposta": "Un angle de 90 graus"},
            {"pregunta": "Quin és el resultat de 5! (factorial de 5)?",
             "opcions": ["120", "25", "60"], "resposta": "120"},
            {"pregunta": "Què és una matriu identitat?",
             "opcions": ["Una matriu quadrada amb 1 a la diagonal i 0 als altres", "Una matriu amb tots els elements iguals", "Una matriu amb una sola fila"], "resposta": "Una matriu quadrada amb 1 a la diagonal i 0 als altres"},
            {"pregunta": "Quin és el valor de sin(90 graus)?",
             "opcions": ["0", "0.5", "1"], "resposta": "1"},
            {"pregunta": "Què és una progressió aritmètica?",
             "opcions": ["Una seqüència on cada terme s'obté sumant una constant", "Una seqüència on cada terme és el producte del precedent", "Una seqüència de nombres primers"], "resposta": "Una seqüència on cada terme s'obté sumant una constant"},
            {"pregunta": "Quin és el mínim comú múltiple de 4 i 6?",
             "opcions": ["12", "24", "6"], "resposta": "12"},
            {"pregunta": "Quina és la solució de x² - 5x + 6 = 0?",
             "opcions": ["x=2 i x=3", "x=1 i x=6", "x=-2 i x=-3"], "resposta": "x=2 i x=3"},
            {"pregunta": "Què és un nombre complex?",
             "opcions": ["Un nombre amb part real i part imaginària", "Un nombre amb decimals", "Un nombre enter gran"], "resposta": "Un nombre amb part real i part imaginària"},
            {"pregunta": "Quin és el resultat de ∫(2x dx)?",
             "opcions": ["x² + C", "2x² + C", "x + C"], "resposta": "x² + C"},
            {"pregunta": "Què és una hipotenusa?",
             "opcions": ["El costat més llarg d'un triangle rectangle", "Un angle de 180 graus", "La suma dels angles d'un triangle"], "resposta": "El costat més llarg d'un triangle rectangle"}
        ]
    },
    "3": {
        "nom": "Cultura General",
        "preguntes": [
            {"pregunta": "Quina és la capital d'Espanya?", "opcions": ["Barcelona", "Madrid", "Sevilla"], "resposta": "Madrid"},
            {"pregunta": "Qui va escriure 'Don Quixot'?", "opcions": ["Miguel de Cervantes", "Gabriel García Márquez", "Pablo Neruda"], "resposta": "Miguel de Cervantes"},
            {"pregunta": "Quin és l'idioma oficial del Brasil?", "opcions": ["Espanyol", "Portuguès", "Francès"], "resposta": "Portuguès"},
            {"pregunta": "Quin és el riu més llarg del món?", "opcions": ["Nil", "Amazones", "Iang-Tsé"], "resposta": "Amazones"},
            {"pregunta": "Qui va ser el primer home a trepitjar la Lluna?", "opcions": ["Neil Armstrong", "Buzz Aldrin", "Iuri Gagarin"], "resposta": "Neil Armstrong"},
            {"pregunta": "En quin any va començar la Segona Guerra Mundial?", "opcions": ["1939", "1914", "1945"], "resposta": "1939"},
            {"pregunta": "Quin país té una bandera amb una estrella blanca sobre fons vermell?", "opcions": ["Turquia", "Xina", "Vietnam"], "resposta": "Turquia"},
            {"pregunta": "Quin és l'element químic amb símbol 'O'?", "opcions": ["Or", "Oxigen", "Osmi"], "resposta": "Oxigen"},
            {"pregunta": "Qui va pintar la Mona Lisa?", "opcions": ["Leonardo da Vinci", "Pablo Picasso", "Vincent van Gogh"], "resposta": "Leonardo da Vinci"},
            {"pregunta": "Quin és el planeta més gran del sistema solar?", "opcions": ["Júpiter", "Saturn", "Neptú"], "resposta": "Júpiter"},
            {"pregunta": "Quina obra literària és famosa per la frase 'Ser o no ser'?",
             "opcions": ["Hamlet", "Macbeth", "Otelo"], "resposta": "Hamlet"},
            {"pregunta": "Quina és la muntanya més alta del món?",
             "opcions": ["K2", "Everest", "Kangchenjunga"], "resposta": "Everest"},
            {"pregunta": "Qui va ser el líder del moviment d'independència de l'Índia?",
             "opcions": ["Mahatma Gandhi", "Nelson Mandela", "Simón Bolívar"], "resposta": "Mahatma Gandhi"},
            {"pregunta": "Quin és l'idioma més parlat del món per nombre de parlants nadius?",
             "opcions": ["Anglès", "Mandarí", "Espanyol"], "resposta": "Mandarí"},
            {"pregunta": "Què va inventar Alexander Graham Bell?",
             "opcions": ["Telèfon", "Ràdio", "Televisió"], "resposta": "Telèfon"},
            {"pregunta": "Quina és la capital d'Austràlia?",
             "opcions": ["Sydney", "Melbourne", "Canberra"], "resposta": "Canberra"},
            {"pregunta": "En quin continent es troba Egipte?",
             "opcions": ["Àsia", "Àfrica", "Europa"], "resposta": "Àfrica"},
            {"pregunta": "Quin és el símbol químic de l'or?",
             "opcions": ["Au", "Ag", "O"], "resposta": "Au"},
            {"pregunta": "Qui va ser el primer president dels Estats Units?",
             "opcions": ["Abraham Lincoln", "George Washington", "Thomas Jefferson"], "resposta": "George Washington"},
            {"pregunta": "Quin és l'idioma oficial de l'Argentina?",
             "opcions": ["Portuguès", "Espanyol", "Italià"], "resposta": "Espanyol"},
            {"pregunta": "Quin any va caure el mur de Berlín?",
             "opcions": ["1989", "1991", "1975"], "resposta": "1989"},
            {"pregunta": "Qui va escriure 'Cent anys de solitud'?",
             "opcions": ["Gabriel García Márquez", "Pablo Neruda", "Jorge Luis Borges"], "resposta": "Gabriel García Márquez"},
            {"pregunta": "Quina és la moneda oficial del Japó?",
             "opcions": ["Yuan", "Won", "Ien"], "resposta": "Ien"},
            {"pregunta": "Quin és l'océà més gran del món?",
             "opcions": ["Atlàntic", "Índic", "Pacífic"], "resposta": "Pacífic"},
            {"pregunta": "Quin pintor va tallar-se una orella?",
             "opcions": ["Pablo Picasso", "Vincent van Gogh", "Salvador Dalí"], "resposta": "Vincent van Gogh"},
            {"pregunta": "Qui va descobrir Amèrica?",
             "opcions": ["Cristòfor Colom", "Vasco de Gama", "Fernando de Magallanes"], "resposta": "Cristòfor Colom"},
            {"pregunta": "Quin és el país més gran del món per superfície?",
             "opcions": ["Canadà", "Xina", "Rússia"], "resposta": "Rússia"},
            {"pregunta": "Quina és la capital de Canadà?",
             "opcions": ["Toronto", "Montreal", "Ottawa"], "resposta": "Ottawa"},
            {"pregunta": "Qui va escriure 'Romeu i Julieta'?",
             "opcions": ["William Shakespeare", "Charles Dickens", "Jane Austen"], "resposta": "William Shakespeare"},
            {"pregunta": "Quin és l'element més abundant a l'atmosfera terrestre?",
             "opcions": ["Oxigen", "Hidrogen", "Nitrogen"], "resposta": "Nitrogen"}
        ]
    },
    "4": {
        "nom": "Videojocs",
        "preguntes": [
            {"pregunta": "Quin videojoc és conegut pel seu personatge principal anomenat Mario?", "opcions": ["Sonic", "Mario Bros", "Pac-Man"], "resposta": "Mario Bros"},
            {"pregunta": "Quin joc va popularitzar el mode 'Battle Royale'?", "opcions": ["Minecraft", "Fortnite", "Among Us"], "resposta": "Fortnite"},
            {"pregunta": "Quin videojoc és famós per construir amb blocs?", "opcions": ["Tetris", "Minecraft", "Roblox"], "resposta": "Minecraft"},
            {"pregunta": "Quin estudi va crear 'The Legend of Zelda'?", "opcions": ["Nintendo", "Sony", "Microsoft"], "resposta": "Nintendo"},
            {"pregunta": "Quin és el videojoc més venut de tots els temps?", "opcions": ["Minecraft", "GTA V", "Tetris"], "resposta": "Minecraft"},
            {"pregunta": "Quin videojoc té un mode anomenat 'Creative'?", "opcions": ["Minecraft", "Fortnite", "Roblox"], "resposta": "Minecraft"},
            {"pregunta": "En quin videojoc apareix el personatge 'Master Chief'?", "opcions": ["Halo", "Call of Duty", "Overwatch"], "resposta": "Halo"},
            {"pregunta": "Quin joc és conegut per la frase 'The cake is a lie'?", "opcions": ["Portal", "Half-Life", "Bioshock"], "resposta": "Portal"},
            {"pregunta": "Quin joc és un MOBA popular?", "opcions": ["League of Legends", "Fortnite", "Minecraft"], "resposta": "League of Legends"},
            {"pregunta": "Quin joc està ambientat a l'univers de Westeros?", "opcions": ["The Witcher", "Game of Thrones RPG", "Skyrim"], "resposta": "Game of Thrones RPG"},
            {"pregunta": "Quin videojoc presenta una illa anomenada 'Koholint'?", "opcions": ["The Legend of Zelda: Link's Awakening", "Mario Kart", "Final Fantasy"], "resposta": "The Legend of Zelda: Link's Awakening"},
            {"pregunta": "Qui és l'antagonista principal a 'Resident Evil'?", "opcions": ["Albert Wesker", "Chris Redfield", "Leon Kennedy"], "resposta": "Albert Wesker"},
            {"pregunta": "Quin és el nom del joc on construeixes i sobrevius en un món pixelat?", "opcions": ["Terraria", "Minecraft", "Roblox"], "resposta": "Minecraft"},
            {"pregunta": "Quin joc utilitza un sistema de cartes anomenat 'Gwent'?", "opcions": ["The Witcher 3", "Hearthstone", "Magic: The Gathering"], "resposta": "The Witcher 3"},
            {"pregunta": "Quin joc és famós per la seva dificultat i el seu mode 'Dark Souls'?", "opcions": ["Bloodborne", "Dark Souls", "Sekiro"], "resposta": "Dark Souls"},
            {"pregunta": "Quin és el nom del mode multijugador de 'Call of Duty' més popular?", "opcions": ["Zombies", "Battle Royale", "Multijugador estàndard"], "resposta": "Multijugador estàndard"},
            {"pregunta": "Quina consola va desenvolupar Sony?", "opcions": ["PlayStation", "Xbox", "Nintendo Switch"], "resposta": "PlayStation"},
            {"pregunta": "Quin és el nom del protagonista a 'Halo'?", "opcions": ["Master Chief", "Marcus Fenix", "Solid Snake"], "resposta": "Master Chief"},
            {"pregunta": "Quin joc té personatges anomenats 'Champions'?", "opcions": ["League of Legends", "Overwatch", "Dota 2"], "resposta": "League of Legends"},
            {"pregunta": "Quin videojoc va ser creat per Mojang?", "opcions": ["Minecraft", "Fortnite", "Terraria"], "resposta": "Minecraft"},
            {"pregunta": "Quin és el joc més venut de la franquícia Pokémon?",
             "opcions": ["Pokémon GO", "Pokémon Roig/Blau", "Pokémon Diamant/Perla"], "resposta": "Pokémon Roig/Blau"},
            {"pregunta": "Quina és la consola més venuda de la història?",
             "opcions": ["PlayStation 2", "Nintendo DS", "PlayStation 4"], "resposta": "PlayStation 2"},
            {"pregunta": "Quin personatge és la mascota de Sega?",
             "opcions": ["Sonic", "Mario", "Crash Bandicoot"], "resposta": "Sonic"},
            {"pregunta": "En quin any es va llançar el primer Grand Theft Auto (GTA)?",
             "opcions": ["1997", "2001", "2004"], "resposta": "1997"},
            {"pregunta": "Quin joc va introduir el sistema de batalla per torns?",
             "opcions": ["Final Fantasy", "Dragon Quest", "Chrono Trigger"], "resposta": "Dragon Quest"},
            {"pregunta": "Quina empresa va crear el joc Fortnite?",
             "opcions": ["EA", "Epic Games", "Ubisoft"], "resposta": "Epic Games"},
            {"pregunta": "Quin és el nom del món obert de la sèrie The Legend of Zelda: Breath of the Wild?",
             "opcions": ["Hyrule", "Termina", "Skyloft"], "resposta": "Hyrule"},
            {"pregunta": "Quina és l'arma característica de Doomguy?",
             "opcions": ["BFG 9000", "Llançacoets", "Escopeta"], "resposta": "BFG 9000"},
            {"pregunta": "Quin joc té el lema 'Gotta Catch 'Em All'?",
             "opcions": ["Digimon", "Pokémon", "Yu-Gi-Oh!"], "resposta": "Pokémon"}
        ]
    }
}

# Variables globals
preguntes_seleccionades = []
score = 0
highscore = 0
dificultat_multiplier = 1
TIME_LIMIT = 30

class Player:
    def __init__(self, nom, HP, LVL, ATTACK, defensa=0, potions=3, atac_especial=0):
        self.nom = nom
        self.HP = HP
        self.LVL = LVL
        self.ATTACK = ATTACK
        self.defensa = defensa
        self.potions = potions
        self.atac_especial = atac_especial

class Monster:
    def __init__(self, nom, HP, LVL, ATTACK, art, tipus="normal", debilitat=None):
        self.nom = nom
        self.HP = HP
        self.LVL = LVL
        self.ATTACK = ATTACK
        self.art = art
        self.tipus = tipus
        self.debilitat = debilitat

def barra_estat():
    print("\n🧑‍💻 Estat del jugador:")
    print("╔═══════════════════════════╗")
    print(f"║ ❤️  Vida: {player.HP:<16}║")
    print(f"║ ⚔️  Atac: {player.ATTACK:<15}║")
    print(f"║ 🛡️  Defensa: {player.defensa:<12}║")
    print(f"║ 📈 Nivell: {player.LVL:<14}║")
    print(f"║ 🧪 Poció: {player.potions:<15}║")
    print("╚═══════════════════════════╝")

def imprimir_titol():
    print(r"""
 _________            .___
 \_   ___ \  ____   __| _/____   _____   ____   ____
 /    \  \/ /  _ \ / __ |/ __ \ /     \ /  _ \ /    \
 \     \___(  <_> ) /_/ \  ___/|  Y Y  (  <_> )   |  \
  \______  /\____/\____ |\___  >__|_|  /\____/|___|  /
         \/            \/    \/      \/            \/
 ________          _____              __      __  .__                            .__  .__ ._._.
 \______ \   _____/ ____\____ _____ _/  |_  _/  |_|  |__   ____   _____   _____  |  | |  || | |
  |    |  \_/ __ \   __\/ __ \\__  \\   __\ \   __\  |  \_/ __ \ /     \  \__  \ |  | |  || | |
  |    `   \  ___/|  | \  ___/ / __ \|  |    |  | |   Y  \  ___/|  Y Y  \  / __ \|  |_|  |_\|\|
 /_______  /\___  >__|  \___  >____  /__|    |__| |___|  /\___  >__|_|  / (____  /____/____/___
         \/     \/          \/     \/                  \/     \/      \/       \/          \/\/
               ⚔️  BENVINGUT A CODEMON ⚔️
""")

def seleccionar_categoria():
    global preguntes_seleccionades
    clear_screen()
    imprimir_titol()
    print("\nSelecciona una categoria de preguntes:")
    for clau, categoria in categorias_preguntas.items():
        print(f"{clau}. {categoria['nom']}")

    while True:
        opcio = input("\nTria una categoria (1-4): ")
        if opcio in categorias_preguntas:
            preguntes_seleccionades = categorias_preguntas[opcio]["preguntes"]
            print(f"\nHas seleccionat: {categorias_preguntas[opcio]['nom']}")
            input("\nPrem ENTER per continuar...")
            return
        else:
            print("Opció no vàlida. Si us plau, tria una categoria del 1 al 4.")

def seleccionar_dificultat():
    global dificultat_multiplier
    clear_screen()
    imprimir_titol()
    print("\nSelecciona la dificultat:")
    print("1. Fàcil (x0.8 dany enemic)")
    print("2. Normal (x1.0 dany enemic)")
    print("3. Difícil (x1.5 dany enemic)")
    print("4. Èpic (x2.0 dany enemic)")

    while True:
        opcio = input("\nTria una dificultat (1-4): ")
        if opcio == "1":
            dificultat_multiplier = 0.8
            print("\nDificultat FÀCIL seleccionada!")
            break
        elif opcio == "2":
            dificultat_multiplier = 1.0
            print("\nDificultat NORMAL seleccionada!")
            break
        elif opcio == "3":
            dificultat_multiplier = 1.5
            print("\nDificultat DIFÍCIL seleccionada!")
            break
        elif opcio == "4":
            dificultat_multiplier = 2.0
            print("\nDificultat ÈPIC seleccionada!")
            break
        else:
            print("Opció no vàlida.")

    input("\nPrem ENTER per continuar...")

def mostrar_menu_principal():
    while True:
        clear_screen()
        imprimir_titol()
        print("\nMENÚ PRINCIPAL")
        print("1. Nova Partida")
        print("2. Puntuacions")
        print("3. Sortir")

        opcio = input("\nTria una opció: ")

        if opcio == "1":
            return True
        elif opcio == "2":
            mostrar_puntuacions()
        elif opcio == "3":
            print("\nFins aviat, heroi!")
            sys.exit()
        else:
            print("Opció no vàlida. Torna a intentar.")
            input("Prem ENTER per continuar...")

def mostrar_puntuacions():
    clear_screen()
    print("🏆 MILLORS PUNTUACIONS 🏆")
    # Això podria llegir d'un fitxer en una versió més avançada
    print("\n1. Guifré - 1200 punts")
    print("2. Laia - 950 punts")
    print("3. Oriol - 780 punts")
    print("4. Marta - 650 punts")
    print("5. Marc - 520 punts")
    input("\nPrem ENTER per tornar al menú...")

items = {
    "1": {"nom": "Poció de vida (+30 HP)", "cost": 50, "efecte": lambda jugador: setattr(jugador, 'HP', jugador.HP + 30)},
    "2": {"nom": "Espasa afilada (+5 ATK)", "cost": 75, "efecte": lambda jugador: setattr(jugador, 'ATTACK', jugador.ATTACK + 5)},
    "3": {"nom": "Armadura resistent (+20 DEF)", "cost": 100, "efecte": lambda jugador: setattr(jugador, 'defensa', jugador.defensa + 20)},
    "4": {"nom": "Poció d'atac especial (1 ús)", "cost": 150, "efecte": lambda jugador: setattr(jugador, 'atac_especial', jugador.atac_especial + 1)}
}

def botiga():
    global score
    clear_screen()
    print("🏪 BOTIGA DEL HEROI")
    print(f"Tens {score} punts per gastar\n")
    for clau, item in items.items():
        print(f"{clau}. {item['nom']} - {item['cost']} punts")

    print("0. Tornar al joc")

    while True:
        tria = input("\nTria un objecte per comprar o 0 per sortir: ")
        if tria == "0":
            break
        if tria in items:
            item = items[tria]
            if score >= item["cost"]:
                score -= item["cost"]
                item["efecte"](player)
                print(f"Has comprat {item['nom']}!")
            else:
                print("No tens punts suficients!")
        else:
            print("Opció no vàlida!")

        input("Prem ENTER per continuar a la botiga...")
        clear_screen()
        print("🏪 BOTIGA DEL HEROI")
        print(f"Tens {score} punts per gastar\n")
        for clau, item in items.items():
            print(f"{clau}. {item['nom']} - {item['cost']} punts")
        print("0. Tornar al joc")

def generar_monstre(nivell):
    # Si el nivell és múltiple de 5, surt un cap
    if nivell % 5 == 0:
        nom_boss = random.choice(list(bosses.keys()))
        boss = bosses[nom_boss]
        return Monster(nom_boss, boss["HP"], boss["LVL"], boss["ATTACK"], boss["art"], "cap")

    # Monstre normal
    nom = random.choice(list(monster_ascii.keys()))
    base_HP = random.randint(20, 30) + nivell * 5
    base_ATK = random.randint(5, 10) + nivell * 2
    base_LVL = nivell
    art = monster_ascii[nom]
    HP = int(base_HP * dificultat_multiplier)
    ATTACK = int(base_ATK * dificultat_multiplier)

    # Assignar tipus i debilitats
    tipus = random.choice(["foc", "aigua", "planta", "llamp"])
    debilitat = {"foc": "aigua", "aigua": "planta", "planta": "foc", "llamp": "terra"}.get(tipus, None)

    return Monster(nom, HP, base_LVL, ATTACK, art, tipus, debilitat)

def atac():
    global player, monster1, score

    # Seleccionar pregunta aleatòria
    pregunta = random.choice(preguntes_seleccionades)

    clear_screen()
    print(f"{player_art}      {monster1.art}")
    barra_estat()

    # Mostrar tipus del monstre
    if monster1.tipus != "normal":
        print(f"\n⚠️  Tipus del monstre: {monster1.tipus.upper()}")
        if monster1.debilitat:
            print(f"💢 Debilitat: {monster1.debilitat.upper()}")

    print(f"\n🔥 {pregunta['pregunta']}")
    for idx, opcio in enumerate(pregunta["opcions"], 1):
        print(f"{idx}. {opcio}")

    print("\n⏳ Temps límit: " + str(TIME_LIMIT) + " segons")
    print("\nACCIONS DE COMBAT:")
    print("1. Atac bàsic (100% encert, dany normal)")
    print("2. Atac fort (75% d'encert, 1.5x dany)")
    print("3. Defensa (redueix dany al proper atac)")
    print("4. Utilitzar poció (+30 HP)")

    if player.atac_especial > 0:
        print(f"5. Atac especial (2.5x dany) - Disponibles: {player.atac_especial}")

    accio = None
    while True:
        try:
            accio = input("\nTria una acció (1-5): ")
            if accio == "4" and player.potions <= 0:
                print("No tens poció!")
                continue
            if accio == "5" and player.atac_especial <= 0:
                print("No tens atacs especials!")
                continue
            if accio not in ["1", "2", "3", "4", "5"]:
                raise ValueError
            break
        except ValueError:
            print("Opció no vàlida, torna a intentar.")

    # Utilitzar poció
    if accio == "4":
        player.HP += 30
        player.potions -= 1
        print(f"\n🧪 Has utilitzat una poció! Vida actual: {player.HP}")
        input("\nPrem ENTER per continuar...")
        return

    defensa_activa = False
    start_time = time.time()

    try:
        resposta_usuari = input(f"\nRespon la pregunta: ")
        elapsed = time.time() - start_time
        if elapsed > TIME_LIMIT:
            raise TimeoutError
        resposta_usuari = int(resposta_usuari)
    except (ValueError, TimeoutError):
        print("\n❌ Temps exhaurit o resposta incorrecta! El monstre ataca!")
        dany = dany_monstre(monster1)
        player.HP -= max(0, dany - player.defensa)
        if player.HP < 0:
            player.HP = 0
        print(f"Vida restant del jugador: {player.HP}")
        input("\nPrem ENTER per continuar...")
        return

    correcte = (1 <= resposta_usuari <= len(pregunta["opcions"]) and \
               pregunta["opcions"][resposta_usuari - 1] == pregunta["resposta"])

    if accio == "3":  # Defensa
        defensa_activa = True
        print("\n🛡️ Defensa activada! El proper atac del monstre farà menys dany.")
        dany = dany_monstre(monster1) // 2
        player.HP -= max(0, dany - player.defensa)
        if player.HP < 0:
            player.HP = 0
        print(f"\nEl monstre ataca amb dany reduït! Vida restant: {player.HP}")
        input("\nPrem ENTER per continuar...")
        return

    if not correcte:
        print("\n❌ Incorrecte! El monstre ataca!")
        dany = dany_monstre(monster1)
        dany_final = max(0, dany - player.defensa)
        player.HP -= dany_final
        if player.HP < 0:
            player.HP = 0
        print(f"Dany rebut: {dany_final} | Vida restant: {player.HP}")
    else:
        multiplicador_dany = 1.0

        # Determinar multiplicador segons l'acció
        if accio == "2":  # Atac fort
            if random.random() <= 0.75:
                multiplicador_dany = 1.5
            else:
                print("\n❌ Atac fort fallat! El monstre ataca!")
                dany = dany_monstre(monster1)
                dany_final = max(0, dany - player.defensa)
                player.HP -= dany_final
                if player.HP < 0:
                    player.HP = 0
                print(f"Dany rebut: {dany_final} | Vida restant: {player.HP}")
                input("\nPrem ENTER per continuar...")
                return

        elif accio == "5":  # Atac especial
            multiplicador_dany = 2.5
            player.atac_especial -= 1
            print("\n💥 ATAC ESPECIAL ACTIVAT!")

        # Càlcul del dany
        dany = dany_jugador(player) * multiplicador_dany

        # Crític aleatori (10% de probabilitat)
        if random.random() < 0.1:
            dany *= 1.8
            print("\n💥 COP CRÍTIC! 💥")

        # Aplicar dany
        monster1.HP -= dany
        print(f"\n✅ Correcte! Fas {int(dany)} de dany al monstre!")

        # Comprovació de debilitat
        if monster1.debilitat and accio == "5":
            print(f"💢 L'atac especial explota la debilitat del monstre!")
            monster1.HP -= dany * 0.5

    if monster1.HP < 0:
        monster1.HP = 0
    print(f"Vida restant del monstre: {monster1.HP}")

    input("\nPrem ENTER per continuar...")

def dany_monstre(monstre):
    # Dany del monstre amb variació aleatòria i possibilitat d'esquivar
    if random.random() < 0.15:  # 15% d'oportunitat d'esquivar
        print("🎯 Has esquivat l'atac del monstre!")
        return 0

    return random.randint(monstre.ATTACK - 5, monstre.ATTACK + 5)

def dany_jugador(jugador):
    # Dany del jugador amb variació aleatòria
    return random.randint(jugador.ATTACK - 3, jugador.ATTACK + 5)

def monstre_mort():
    global score, player
    clear_screen()
    print(f"\n💀 El monstre {monster1.nom} ha estat derrotat!")

    # Recompenses
    punts_base = 25 * monster1.LVL
    punts_extra = 0

    # Recompensa per tipus de monstre
    if monster1.tipus == "cap":
        punts_extra = 200
        print("🏆 HAS DERROTAT UN CAP! +200 PUNTS EXTRA!")
    elif monster1.tipus != "normal":
        punts_extra = random.randint(20, 50)
        print(f"✨ Bonificació per tipus especial! +{punts_extra} punts")

    punts_total = punts_base + punts_extra
    score += punts_total

    # Recompenses aleatòries
    if random.random() < 0.3:  # 30% d'oportunitat
        player.potions += 1
        print("🧪 Has guanyat una poció extra!")

    if random.random() < 0.1:  # 10% d'oportunitat
        player.atac_especial += 1
        print("⚡ Has guanyat un atac especial!")

    print(f"Puntuació actual: {score}")
    input("\nPrem ENTER per continuar...")
    botiga()

def jugador_mort():
    global highscore, score
    clear_screen()
    print("\n☠️ HAS MORT!")

    # Enviar puntuació (en un entorn real)
    dades2 = {"game_id": dades["game_id"], "data": dades, "score": score}
    try:
        requests.post("https://fun.codelearn.cat/hackathon/game/finalize", json=dades2)
    except:
        pass

    if score > highscore:
        highscore = score
        print("🎉 NOU RÈCORD PERSONAL!")
    print(f"🏆 La teva millor puntuació: {highscore}")
    print(f"📊 Puntuació d'aquesta partida: {score}")
    score = 0
    input("\nPrem ENTER per tornar al menú principal...")

def combat():
    global monster1, player

    while player.HP > 0 and monster1.HP > 0:
        clear_screen()
        print(f"{player_art}      {monster1.art}")
        barra_estat()
        print(f"\n💥 {player.nom} vs {monster1.nom} - Nivell {monster1.LVL}")

        atac()

    if monster1.HP <= 0:
        monstre_mort()
        # Pujar de nivell i generar nou monstre
        player.LVL += 1
        player.HP = min(100 + player.LVL * 10, 300)  # Vida màxima 300
        player.ATTACK = 10 + player.LVL * 3
        monster1 = generar_monstre(player.LVL)
        return "continuar"

    if player.HP <= 0:
        jugador_mort()
        return "mort"

def nova_partida():
    global player, monster1, score
    seleccionar_categoria()
    seleccionar_dificultat()

    score = 0
    nom_jugador = input("Introdueix el teu nom, heroi: ")
    player = Player(nom_jugador, 100, 1, 15, defensa=10, potions=3, atac_especial=0)
    monster1 = generar_monstre(player.LVL)
    clear_screen()
    imprimir_titol()
    input("Prem ENTER per començar la batalla!")

    estat = "continuar"
    while estat == "continuar":
        estat = combat()

    if estat == "mort":
        return

# Programa principal
if __name__ == "__main__":
    while True:
        if mostrar_menu_principal():
            nova_partida()

